### PR TITLE
Fix #88 use correct type for variadic

### LINKED ISSUE #88: Test failure on BigEndian
Trying to build on PowerPC computer

```
+ /usr/bin/php -d extension=/builddir/build/BUILDROOT/php-pecl-ds-1.1.10-1.fc27.ppc64/usr/lib64/php/modules/ds.so /usr/bin/phpunit --bootstrap tests/autoload.php tests
PHPUnit 5.7.21 by Sebastian Bergmann and contributors.
PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 549755813776 bytes) in /builddir/build/BUILD/php-pecl-ds-1.1.10/tests/tests/DequeTest.php on line 64
```

Will try to investigate (as soon as I will be able to get access to a PowerPC machine)

P.S. fails on ppc64, ok on ppc64le.

### PR DESCRIPTION
**Pull request by remicollet**
Dont know which is the correct branch...

See #98 for comment

### CODE REVIEW

**Comment by rtheunissen** [comment]
All tests passing, @remicollet. Thank you so much. ✨

**Comment by remicollet** [comment]
@rtheunissen do you plan a new release soon ?

(FYI, I plan to submit this extension for Fedora official repository, so have to choice between waiting for new release, of submitted current release with this patch applied)

**Comment by rtheunissen** [comment]
@remicollet I've been working on making progress towards 2.0. 

I'll tag and release master now.

**Comment by rtheunissen** [comment]
@remicollet tagged and released as [v1.2.3](https://pecl.php.net/package/ds/1.2.3).

**Comment by remicollet** [comment]
thanks

**Comment by remicollet** [comment]
@rtheunissen FYI: https://bugzilla.redhat.com/show_bug.cgi?id=1482013

**Pull request merged**
